name: Minify CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Minify CSS
        run: pnpm run minify
