name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          version: latest
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun run build
      - run: bun publish
