name: Publish to npm

on:
  release:
    types:
      - created

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          version: latest

      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: latest
          cache: true
          run_install: true

      - name: Set version from tag
        run: npm version ${GITHUB_REF_NAME#v} --no-git-tag-version

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --no-git-check
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
